#!/usr/bin/env node
import { fileURLToPath } from "node:url";
import fs from "node:fs";import path from "node:path";import {spawnSync} from "node:child_process";
const root=process.cwd();const thisFile=fileURLToPath(import.meta.url);const failures=[];const reqSkills=["divan-brand-art-direction","divan-cinematic-threshold","divan-book-motion-system","divan-atmosphere-effects","divan-mobile-performance-guard","divan-accessibility-qa","divan-asset-pipeline-higgsfield","divan-release-gauntlet"];
const reqFiles=[".claude/settings.json",".claude/divan-project.json",".claude/agents/divan-sonnet-specialist.md",".claude/hooks/guard-protected-input.sh",".claude/hooks/check-touched-frontend.sh",".claude/hooks/final-cinematic-gate.sh",".claude/scripts/path-policy.mjs",".claude/scripts/guard-tool-input.mjs",".claude/scripts/capture-protected-baseline.mjs",".claude/scripts/check-protected-diff.mjs",".claude/scripts/configure-divan-project.mjs",".claude/scripts/create-asset-manifest.mjs",".claude/scripts/check-media-budget.mjs",".claude/scripts/check-verification-report.mjs",".claude/scripts/worktree-state-hash.mjs",".claude/scripts/run-divan-gate.sh",".claude/scripts/arm-release-gate.sh",".claude/scripts/activate-cinematic-task.sh",".claude/scripts/deactivate-cinematic-task.sh",".claude/templates/divan-cinematic-enhancement-report.md"];
for(const s of reqSkills)reqFiles.push(`.claude/skills/${s}/SKILL.md`);for(const f of reqFiles)if(!fs.existsSync(path.join(root,f)))failures.push(`missing ${f}`);
let settings={};try{settings=JSON.parse(fs.readFileSync(path.join(root,".claude/settings.json"),"utf8"));}catch(e){failures.push(`settings JSON: ${e.message}`)}if(settings.model!=="fable")failures.push("settings.model must be fable");if(!["low","medium","high","xhigh"].includes(settings.effortLevel))failures.push("persisted effortLevel must be low, medium, high, or xhigh");
const agent=fs.readFileSync(path.join(root,".claude/agents/divan-sonnet-specialist.md"),"utf8");if(!agent.includes("model: claude-sonnet-5"))failures.push("Sonnet specialist must pin claude-sonnet-5");if(!agent.includes("maxTurns: 24"))failures.push("Sonnet specialist maxTurns must be 24");
function allFiles(dir){let a=[];for(const e of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,e.name);if(e.isDirectory())a=a.concat(allFiles(p));else a.push(p);}return a;}
for(const f of allFiles(path.join(root,".claude"))){const text=fs.readFileSync(f,"utf8");if(path.resolve(f)!==path.resolve(thisFile)){if(/\b(?:TBD|FIXME)\b/.test(text))failures.push(`${path.relative(root,f)} unfinished marker`);if(text.includes("�")||text.includes("[Shared style preamble]")||text.includes("<current-job-set-type>"))failures.push(`${path.relative(root,f)} unresolved text`);}if(f.endsWith(".mjs")){const r=spawnSync(process.execPath,["--check",f],{encoding:"utf8"});if(r.status!==0)failures.push(`${path.relative(root,f)} node syntax`);}if(f.endsWith(".sh")){const r=spawnSync("bash",["-n",f],{encoding:"utf8"});if(r.status!==0)failures.push(`${path.relative(root,f)} shell syntax`);}}
if(failures.length){console.error("DIVAN pack validation failed:\n"+failures.map(x=>`- ${x}`).join("\n"));process.exit(1);}console.log(`DIVAN pack validation PASS: ${reqSkills.length} skills and ${reqFiles.length} required files.`);
